### PR TITLE
Stable/mitaka

### PR DESCRIPTION
**Pull request by hiago-miguel**
## Added Compatibility to Fuel 9

- Changed compatible releases in the metadata file
- Changed package version to 3.0.0
- tasks.yaml file replaced by deployment_tasks.yaml
- Fixed some broken links and referencies in the documentation

### CODE REVIEW

**Comment by dancn** [comment]
Hello Miguel,
thanks for submitting the pull request.
The request seems almost fine.

I do not understand the renames in the doc/s dir in 4984322
Could you explain them?

Thanks

**Comment by hiago-miguel** [comment]
Hi dancn,

Sorry about this commit. My bad
I'll remove it (https://github.com/SmartInfrastructures/fuel-plugin-novadocker/commit/4984322dc5a03063c8d2016b6043e6103a9595dc) , and redo the changes without the renames in the docs dir. Then I'll submit a new pull request, ok?

**Comment by dancn** [comment]
> I'll remove it (4984322) , and redo the changes without the renames in the docs dir. Then I'll submit a new pull request, ok?

Yes, please.
I will create a 9.0 branch for the merge!

Thanks

**Comment by hiago-miguel** [comment]
I did the changes. I'll close this request and open another!

**Pull request closed without merging**
